// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlLZLZEB7-3nSSgSnP5x_a0QXU7_0uCe4',
    appId: '1:624022406296:web:9c41b14d3412cb399fbced',
    messagingSenderId: '624022406296',
    projectId: 'payment-getways',
    authDomain: 'payment-getways.firebaseapp.com',
    storageBucket: 'payment-getways.appspot.com',
    measurementId: 'G-ESHM075BQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH3rOwNI8tuq-6iknJUYSo5QOSLNx-lxw',
    appId: '1:624022406296:android:56e43dc3ef603ed79fbced',
    messagingSenderId: '624022406296',
    projectId: 'payment-getways',
    storageBucket: 'payment-getways.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl5Vc2_2Pu_QDFt6kARWNJDs2dC1CfpAM',
    appId: '1:624022406296:ios:3137747dc40a0f409fbced',
    messagingSenderId: '624022406296',
    projectId: 'payment-getways',
    storageBucket: 'payment-getways.appspot.com',
    iosBundleId: 'com.example.paymentsGetway',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl5Vc2_2Pu_QDFt6kARWNJDs2dC1CfpAM',
    appId: '1:624022406296:ios:3137747dc40a0f409fbced',
    messagingSenderId: '624022406296',
    projectId: 'payment-getways',
    storageBucket: 'payment-getways.appspot.com',
    iosBundleId: 'com.example.paymentsGetway',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlLZLZEB7-3nSSgSnP5x_a0QXU7_0uCe4',
    appId: '1:624022406296:web:893f88f54da8c3bf9fbced',
    messagingSenderId: '624022406296',
    projectId: 'payment-getways',
    authDomain: 'payment-getways.firebaseapp.com',
    storageBucket: 'payment-getways.appspot.com',
    measurementId: 'G-MM3WHK2RV1',
  );
}
